spring:
  session:
    jdbc:
      initialize-schema: always
    store-type: jdbc
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true # SQL에 색상을 입혀서 터미널에서 더 잘 보이게 만듭니다.
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/api?serverTimezone=Asia/Seoul
    username: root
    password:
    hikari:
      maximum-pool-size: 40

logging:
  level:
    org.hibernate.SQL: debug          # 실행되는 SQL을 출력
    org.hibernate.orm.jdbc.bind: trace # (선택) SQL에 들어가는 파라미터 값을 출력